// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDduaceJO1HPSeqrKCu58IH0izgqIZihSw',
    appId: '1:92440660406:web:719beca00405430e7b9917',
    messagingSenderId: '92440660406',
    projectId: 'scholar-ai-7884a',
    authDomain: 'scholar-ai-7884a.firebaseapp.com',
    storageBucket: 'scholar-ai-7884a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSfJ27B3hDcCXhG-l896VQyC9lz-Z0iw4',
    appId: '1:92440660406:android:8c6cb3d6d22574937b9917',
    messagingSenderId: '92440660406',
    projectId: 'scholar-ai-7884a',
    storageBucket: 'scholar-ai-7884a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYrpf-M2773pMZkdyYWU5033uXI9t0R7Q',
    appId: '1:92440660406:ios:920239cde614d96f7b9917',
    messagingSenderId: '92440660406',
    projectId: 'scholar-ai-7884a',
    storageBucket: 'scholar-ai-7884a.appspot.com',
    iosBundleId: 'com.example.scholarAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYrpf-M2773pMZkdyYWU5033uXI9t0R7Q',
    appId: '1:92440660406:ios:6c8ef2b63d316fb97b9917',
    messagingSenderId: '92440660406',
    projectId: 'scholar-ai-7884a',
    storageBucket: 'scholar-ai-7884a.appspot.com',
    iosBundleId: 'com.example.scholarAi.RunnerTests',
  );
}
